meteor/galaxy-docs

README.md, site/package.json
- Add documentation of git submodule
- Don't require globally installed hexo-cli
This is now identical to apollo-docs (except for needing to go into the
site subdirectory)
=> Update README and don't require global installs

content/support.md
Explaining that Galaxy's support focus is Galaxy and not Meteor, and if Meteor is your focus, consider devsub, or the forums or relevant GitHub pages.
=> Updated the support language.

content/seo.md
Changing the docs to omit this, since they currently tell users you can see the prerender tokens in the logs, and one user wrote in asking what he did wrong (6397).
=> The newer versions of mdg:seo don't print the prerender token in logs

content/encryption.md
Per the changes in meteor/meteor#8268 and meteor/guide#605, this discourages the use of `force-ssl` by removing the recommendation and providing the Galaxy-recommended instruction.
/cc @glasser
=> Stop recommending the use of `force-ssl`

content/transfer-apps.md
Rebased to master (you can delete update...1.3 branch, which wasn't) and made the > 1.3 change so doc is no longer outdated now that we're on Meteor 1.4.
=> Added > to indicate transfer instructions work for Meteor > 1.3

content/support.md
Clarifies the meaning of critical ticket. As it is, it appears that
app downtime, or anything the user judges to be sufficiently serious,
qualifies as a critical ticket.
=> Support: Clarified the meaning of critical ticket.

content/deploy-guide.md, content/mongodb.md
PR to add a recommendation to use MongoDB Atlas for hosting your MongoDB.
Similar PR made on the Meteor Guide which has been accepted and merged: https://github.com/meteor/guide/pull/609
**Changes made:**
- Added recommendation for MongoDB Atlas as a MongoDB hosting service.
- Added hyperlink to detailed step-by-step guide to setting up MongoDB Atlas for a Meteor app deployed with Galaxy.
- Removed unnecessary whitespaces from end of lines.
@julianeon Let me know if there is anything I can do to help this PR get accepted and merged. 🙂
=> Mongodb deploy mongodb atlas

content/scaling.md
Node options are mentioned as an option you can change before they are
explained, later in the article. Now that part of the article links to
the explanation, so you can continue reading where it's defined.
=> Changes node options to link to relevant section.

content/mongodb.md
Adding what is usually sent to users in MongoDB troubleshooting cases
to the MongoDB document.
=> Mongodb: Adding troubleshooting tips

content/deploy-troubleshooting.md
Changed the language slightly to be more clear about what a deployment
failure is. Also changed the language around when this is noted in the
logs. Overall very slight changes.
=> Troubleshooting: deployment failure

content/deploy-troubleshooting.md
Now with a more accurate explanation of what causes a 502 error, and
clearer language around what exactly is failing and how.
=> Troubleshooting: clarification on 502 and language

content/app.md
Changed the app article to now refer to the container article (as it
already did) but also the container environment article, and the logs article.
=> Links to container and logs article from app article

content/custom-domains.md, content/deploy-guide.md, content/deploy-quickstart.md
Formerly regions were referred to as us-east-1 and eu-west-1. This
commit changes that to US East and EU West, as that's easier to read
on the page and flows better.
=> Region consistency (across docs)

content/billing.md
Clarifying billing so it's more clear what happens and when - billing
for the previous month at the start of the new month.
=> Billing: stopping and starting

content/deploy-quickstart.md
Now clearer that the deployment command isn't 'all-purpose' but is
different for different regions.
=> Quickstart: Changed to make the region specificity more clear.

content/scaling.md
To allow sections to be more easily linked to when sent in emails and
included in docs.
=> Scaling section headings

site/_config.yml, site/assets/theme-colors.less, site/package.json
This changes the theme submodule to be the current version of https://github.com/meteor/hexo-theme-meteor/, which the current theme is also based on, but has iterated substantially since.
All existing features should still work properly but I've added the `_config.yml` necessary to properly theme it for the Galaxy Guide (links, logo, etc.).
=> Update the theme to be consistent with the other Meteor themes.

content/base-image-packages.md, content/container-environment.md, content/custom-base-images.md, content/deploy-region.md, content/environment-variables.md, site/_config.yml, site/package-lock.json
This is now ready for release. We needed to:
=> Document the container environment, custom base images, healthchecking, and the behavior of the default base image

content/logs.md
=>  Fix syntax highlighting in `logs.md`

package-lock.json, package.json
I'm not sure where we actually render Jade files, but there are none
present in this repository.  As one of its transitive dependencies is an
aging version of `uglify-js`, which GitHub suggests has a
"vulnerability" (which wouldn't affect this site anyway, since it's
static), I'm removing it from the dependency graph.
=> Remove `hexo-renderer-jade`, as we have no `.jade` files here.

package.json
While these two renovate configuration extensions, `apollo-docs`[0] `meteor-docs`[1] are _very_ similar, they are intentionally different and this was certainly a result of me copying and pasting the wrong configuration.  There is currently one outstanding PR (https://github.com/meteor/galaxy-docs/pull/140) which would have been automatically merged, had I used the right configuration.
[0] https://github.com/apollographql/renovate-config-apollo-docs
[1] https://github.com/meteor/renovate-config-meteor-docs
=> Change Renovate config from `apollo-docs` to `meteor-docs`.

_config.yml
This property is normally set on a Meteor-wide level by the
`meteor-hexo-config`[0] package, but had previously been getting explicitly
undefined with this empty YAML `docsearch` property.
This should re-enable search on the Galaxy Guide. 🎉 
(See Netlify below to test!)
[0] https://github.com/meteor/meteor-hexo-config
Closes #133
=> Stop clearing the `docsearch` configuration in `_config.yml` (i.e. Re-enable search).

source/apm-make-your-app-faster.md
`meteorhacks:aggregate` seams not maintained anymore and does not work with Meteor 1.7.x. `sakulstra:aggregate` is its maintained fork and works as it should.
See https://github.com/sakulstra/meteor-aggregate#what-the-fork for further details about why the fork has been created and https://github.com/meteorhacks/meteor-aggregate/issues/48#issuecomment-396610701 to see the problem with `meteorhacks:aggregate`
=> change meteorhacks:aggregate into sakulstra:aggregate

source/deploy-to-galaxy.md
The previous description sounds like the cost was per deployment rather than the hours used for a deployment.
=> Clarify deployment costs

source/dns.md
- Removed the section where it says Galaxy does not support a configuration using IP registration.
- I added the section Hosting on a Root Domain using an A Record explaining how to activate the root domain.
To enhance our security and avoid exposure to the entire internet, I refrained from including the IPs in our document.
=> Hosting on a Root Domain using an A Record
