meteor/galaxy-docs

content/base-image-packages.md
- Node version is now dynamic
- Add git
- Fix indentation
=> base-image-packages: update for ImageBuilder, etc

content/cdn.md, content/deploy-guide.md, content/deploy-troubleshooting.md, content/dns.md, content/environment-variables.md, content/index.md
Despite the name, this is a real pull request; I cleaned up the language in a few articles. None of the meaning was changed, but it should read slightly cleaner now.
=> Pull request trial

content/deploy-troubleshooting.md, content/transfer-apps.md
Revisions to the troubleshooting article. In terms of content, the most substantive pull request to date.
=> Troubleshoot

content/deploy-guide.md
Add protocol to mlab & compose external links
=> Fix broken external links

content/billing.md
Made the spacing slightly clearer. Added a "prices are impacted by" paragraph and a "stopping charges" section.
=> Clearer billing language.

content/support.md
Tested w hexo server to be sure it looks good (no formatting breaks or missing pieces, looks better than original version).
=> Fixed a missing period, spacing, a link that said described below, etc.

content/deploy-guide.md
Needs review to confirm factual accuracy.
=> Now including language about deployment tokens.

content/support.md
Changed one paragraph to spell out what business hours are how they are counted.
=> Amended text to mention business hours.

content/deploy-troubleshooting.md
Heavily edited article and added a memory section. Now starts off with a general advice section, explains in more detail the significance of the 503 error, and talks at length about OOM at bottom.
=> Troubleshooting memory

content/seo.md
Now including escaped fragment test by curl to confirm prerender is working.
=> SEO: response to customer and on-call suggestion

content/environment-variables.md
Responing to this user request:
https://github.com/meteor/galaxy-docs/issues/13
Article has been rearranged to make flow & examples more clear.
=> Environment Variables: Changed for consistency.

content/seo.md
Corrected from incorrect version.
=> Correct URL.

content/scaling.md
Changed to include discussion items for scaling and when to scale, as it relates to garbage collection.
=> Scaling: Garbage collection - including node options

content/deploy-guide.md
Explains to deploy to meteorapp.com in US region and eu.meteorapp.com in EU region.
=> Deploy guide: Changed in response to user suggestion re: meteorapp

content/commands.md, site/_config.yml
Article catagloguing all terminal commands that are relevant to Galaxy.
=> Commands: New article

content/commands.md
Changed to have a more consistent format across all commands. Changed
transfer to authorized transfer, and list-sites to list sites, and
added explanatory text.
=> Commands: consistency edit

content/deploy-troubleshooting.md
Now with better spacing and very minor wording changes.
=> Troubleshooting: package.json file edits

content/support.md
Now providing links for GitHub and the forums, and briefly explaining
their use. Also describing in more detail what does and does not
qualify as a Galaxy-supported issue.
=> Support - expanded with GitHub and forums links

content/support.md
Enhanced Galaxy Support and Meteor Developer Support are now more
properly linked, and parallel each other, each on its own page.
=> Support: better links

content/deploy-troubleshooting.md
Now clearer what is being referred to, as requested in the comments.
=> Troubleshooting: changed ours to yours and swapped a few pronouns around.

content/seo.md
Changed the phrasing slightly and made it more clear that we recommend
you sign up for prerender if you need more frequent recaches.
=> SEO: Recaching section rephrasing

content/deploy-troubleshooting.md
The double-nested format was confusing and kind of distracting. It's
now been refactored to only be one level deep, uniformly.
=> Troubleshooting: Condensed formatting

content/deploy-quickstart.md
Now it's more clear that there are two regions: US and EU.
Also changed the billing section slightly to mention you can see your
bills in your account's Settings page.
=> Deploy-quickstart: more region clarity+billing edit.

content/dns.md
Changed an instance of us-east-1 to US East and did the same for EU West.
=> DNS: region name change

content/deploy-troubleshooting.md
What to do if the other conditions in the article don't match. A few
brief tips that will help in those situations where there isn't enough
to go on for troubleshooting.
=> Troubleshooting: Continuing issues

content/support.md
Very minor edits to simplify language and cut out some unnecessary
verbiage.
=> Support: More concise language

content/billing.md
Made the language clearer about what stopping your app does to
billing, vs. deleting, and also tidied up the language.
=> Billing: Clearer about stopping

content/support.md
Now including a section describing in more detail about what is in and
out of scope.
=> Support: Scope discussion

content/security.md
Minor spelling and content revisions.
=> Security Systems Policy Edits

content/security.md
Minor spelling and consistency revisions.
=> Security Revisions

content/security.md
Changed capitalization so it's consistent throughout the article.
=> Security - Minor Changes

content/deploy-troubleshooting.md
Some additions and edits were made to clarify the message and add
information that was missing.
=> Troubleshooting: Refinements

content/deploy-troubleshooting.md
This edit will make it easier to link 502 and 503 sections.
=> Troubleshooting: Section Heading

content/support.md
Clarification that support is email-only.
=> Support - channel

content/deploy-troubleshooting.md
Explaining how Meteor APM can help in memory situations.
=> Meteor APM update

content/billing.md
Clarifying there is no free tier on Galaxy.
=> Billing: tiers

content/deploy-troubleshooting.md
Includes a line and a link now to APM docs at bottom.
=> Troubleshooting w APM

content/dns.md
=> DNS Issues

content/support.md
Explaining how to file a bug in Meteor when you have an issue, or
search for a related issue.
=> Support: filing a bug

content/support.md
Explaining what is and is not supported in a more clear form.
=> Support scope: expanded explanation

content/billing.md
Clarified to explain what this is.
=> Billing Month

content/dns.md
Including a helpful link shared by a community member.
=> DNS: HTTPS on the naked domain

content/deploy-troubleshooting.md
How to file a bug related to Meteor, also adds a link to Stack
Overflow, tag meteor.
=> Troubleshooting: Meteor

content/containers.md
An explanation of why it's a good practice to run multiple containers.
=> Container restarts

content/containers.md
=> Container restart edit

content/containers.md
=> Container restart language

content/billing.md
Methods to save money when using Galaxy.
=> Billing Revision

content/environment-variables.md
=> Environment Variables

content/containers.md
=> Container - Sections

content/seo.md
=> SEO Prerender Testing

content/billing.md
Cleaned up language and explained environment doesn't affect pricing.
=> Billing Clarification

content/support.md
Makes other venues section linkable.
=> Support Scope

content/seo.md
=> Cache Freshness Edit and Sections

content/apm-optimizing-your-app-for-live-queries.md
the goo link was dead... put the real link there
=> Fix broken link

content/seo.md, site/package-lock.json, site/package.json
i think npm install upgraded the hexo version for me ... idk if thats a bad thing, going to leave as is - the site worked on my localhost just fine
=> Specifics on how to configure your own prerender token

content/apm-getting-started.md
=> Removing dead links

content/environment-variables.md
Describing how you can contact support to obscure it.
=> settings.json information

content/environment-variables.md
Mentioning GALAXY_NODE_OPTIONS in the Env Variable article.
=> env-variables-node-options

content/support.md
=> Support terms of service linked

content/environment-variables.md
=> Formatting edit

content/containers.md
Changed restart container line.
=> Update to containers.md

source/logs.md
=> Log storage update

package-lock.json, package.json, renovate.json
Each of the following commits has specific messages!
=> Additional updates for docs auto-management.

source/app.md
=> Update app.md with Meteor APM

source/cdn.md
=> Change "you application" to "your application"

source/apm-make-your-app-faster.md
Replaced broken link with new link to MongoDB Online Course Catalog where Meteor users can learn more about MongoDB concepts including Aggregation.
=> Fix broken link and adjust information.

source/base-image-packages.md
This has been our implicit internal policy for a long time; acknowledge it.
=> Policy of freezing default base image packages

source/mongodb.md
Fixes https://github.com/meteor/guide/issues/1018
=> Fix link to oplog tailing article

source/apm-getting-started.md
To reflect changes in this meteor-apm-agent PR: https://github.com/meteor/meteor-apm-agent/pull/12
=> Instructions on disabling APM

source/changelog.md, source/dns.md
- Enabling SSL by default
- Adding changes to the change log
=> Updating changelog and info about default SSL

source/push-to-deploy.md
=> #9 - M. GA Push to Deploy

source/apm-optimizing-your-app-for-live-queries.md
A small fix to the words used in this docs.
=> apm-optimizing-your-app-for-live-queries.md - Fix wording
